language: node_js
sudo: true
node_js:
  - 8
branches:
  only:
    - master
install:
  - npm install
script:
  - npm run build
before_deploy:
  - cd ./dist
deploy:
  provider: npm
  email: $EMAIL_ADDRESS
  api_key: $NPM_API
  skip_cleanup: true