language: node_js
sudo: false
node_js:
  - 6
  - 5
branches:
  only:
    - master
install:
  - npm install
script:
  - npm run build
deploy:
  provider: npm
  email: $EMAIL_ADDRESS
  api_key: $NPM_API